---
services:

############################
# RADARR: TV show downloader and manager
############################

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /media/arr/radarr/config:/config
      - /media/arr/radarr/movies:/movies #optional
      - /media/arr/qbittorrent/downloads:/downloads #optional
    restart: unless-stopped
    env_file:
      - .env
    
############################
# SONARR: TV show downloader and manager
############################

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /media/arr/sonarr/config:/config
      - /media/arr/sonarr/tvseries:/tv #optional
      - /media/arr/qbittorrent/downloads:/downloads #optional
    restart: unless-stopped
    env_file:
      - .env
    
############################
# PROWLARR: Indexer manager for Sonarr, Radarr, and Lidarr 
############################

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /media/arr/prowlarr/config:/config
    restart: unless-stopped
    env_file:
      - .env

############################
# BAZARR: Subtitle downloader and manager for Sonarr and Radarr  
############################

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /media/arr/bazarr/config:/config
      - /media/arr/radarr/movies:/movies #optional
      - /media/arr/sonarr/tvseries:/tv #optional
    restart: unless-stopped
    env_file:
      - .env
    
############################
# LIDARR: Music downloader and manager for artists and albums
############################

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /media/arr/lidarr/config:/config
      - /media/arr/lidarr/music:/music #optional
      - /media/arr/qbittorrent/downloads:/downloads #optional
    restart: unless-stopped
    env_file:
      - .env
    
############################
# READARR: Ebook and audiobook downloader and manager  
############################

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /media/arr/readarr/config:/config
      - /media/arr/readarr/books:/books #optional
      - /media/arr/qbittorrent/downloads:/downloads #optional
    restart: unless-stopped
    env_file:
      - .env
    
############################
# QBITTORRENT: Torrent client with Web UI for automated downloads  
############################

  #qbittorrent:
  #  image: lscr.io/linuxserver/qbittorrent:latest
  #  container_name: qbittorrent
  #  network_mode: "service:gluetun"
  #  environment:
  #    - PUID=${PUID}
  #    - PGID=${PGID}
  #    - TZ=${TZ}
  #    - WEBUI_PORT=8080
  #    - TORRENTING_PORT=6881
  #  volumes:
  #    - /media/arr/qbittorrent/config:/config
  #    - /media/arr/qbittorrent/downloads:/downloads #optional
  #  restart: unless-stopped
  #  env_file:
  #    - .env

############################
#SABNZBD: Usenet download client with web-based interface
############################
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /media/arr/sabnzbd/config:/config
      #- /mount/nas/data/usenet:/data/usenet #optional
    restart: unless-stopped

############################
# JELLYFIN: Media server for streaming movies, shows, and music 
############################

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /media/arr/jellyfin/config:/config
      - /media/arr/sonarr/tvseries:/data/tvshows
      - /media/arr/radarr/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    env_file:
      - .env

############################
# JELYSEER: Request management interface for Jellyfin users  
############################

  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
      - PORT=5055
    volumes:
      - /media/arr/jellyseerr/config:/app/config
    restart: unless-stopped
    
############################
# GLUETUN: VPN gateway routing container traffic via WireGuard/OpenVPN  
############################

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    ports:
      - 9696:9696 #prowlarr
      - 7878:7878 #radarr
      - 8989:8989 #sonarr
      - 6767:6767 #bazarr
      - 8686:8686 #lidarr
      - 8787:8787 #readarr
      #- 8080:8080 #qbittorrent
      #- 6881:6881 #qbittorrent
      #- 6881:6881/udp #qbittorrent
      - 8080:8080 # sabnzbd
      - 9090:9090 # sabnzbd
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE} # or wireguard
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
    env_file:
      - .env
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 20s
      timeout: 10s
      retries: 5
    restart: unless-stopped
      
############################

